export const houseList = [
  { id: 1, houseType: "3-Bedroom Apartment", location: "City", rentCost: 600, purchaseCost: 40_000, taxRate: 5, image: "scripts/houses/images/three-bed-apt.jpg", sleepQuality: 5, hygieneEffect: 0 },
  { id: 2, houseType: "2-Bedroom Apartment", location: "City", rentCost: 800, purchaseCost: 45_000, taxRate: 5, image: "scripts/houses/images/two-bed-apt.jpg", sleepQuality: 5, hygieneEffect: 0 },
  { id: 3, houseType: "Studio Apartment", location: "City", rentCost: 600, purchaseCost: 40_000, taxRate: 5, image: "scripts/houses/images/studio-apt.jpg", sleepQuality: 4, hygieneEffect: 0 },
  { id: 4, houseType: "Luxury Penthouse", location: "Luxury Estate", rentCost: 2_500, purchaseCost: 200_000, taxRate: 20, image: "scripts/houses/images/lux-penthouse.jpg", sleepQuality: 9, hygieneEffect: 2 },
  { id: 5, houseType: "1-Bedroom Cottage", location: "City", rentCost: 700, purchaseCost: 35_000, taxRate: 5, image: "scripts/houses/images/studio-apart.jpg", sleepQuality: 4, hygieneEffect: 0 },
  { id: 6, houseType: "Family Bungalow", location: "Village", rentCost: 1_500, purchaseCost: 130_000, taxRate: 15, image: "scripts/houses/images/fam-bungalow.jpg", sleepQuality: 6, hygieneEffect: 1 },
  { id: 7, houseType: "4-Bedroom Detached House", location: "City", rentCost: 2_000, purchaseCost: 250_000, taxRate: 20, image: "scripts/houses/images/detached-houses.jpg", sleepQuality: 7, hygieneEffect: 1 },
  { id: 8, houseType: "Loft Apartment", location: "City", rentCost: 900, purchaseCost: 60_000, taxRate: 10, image: "scripts/houses/images/loft-apt.jpg", sleepQuality: 5, hygieneEffect: 0 },
  { id: 9, houseType: "2-Bedroom Condo", location: "Luxury Estate", rentCost: 1_000, purchaseCost: 85_000, taxRate: 10, image: "scripts/houses/images/condo.jpg", sleepQuality: 6, hygieneEffect: 1 },
  { id: 10, houseType: "Studio Cottage", location: "Village", rentCost: 150, purchaseCost: 8_000, taxRate: 5, image: "scripts/houses/images/cottage.jpg", sleepQuality: 3, hygieneEffect: -1 },
  { id: 11, houseType: "1-Bedroom Log Cabin", location: "Village", rentCost: 350, purchaseCost: 20_000, taxRate: 5, image: "scripts/houses/images/log-cabin.jpg", sleepQuality: 4, hygieneEffect: -1 },
  { id: 12, houseType: "2-Bedroom Farmhouse", location: "Village", rentCost: 200, purchaseCost: 10_000, taxRate: 5, image: "scripts/houses/images/farm-house.jpg", sleepQuality: 3, hygieneEffect: -1 },
  { id: 13, houseType: "3-Bedroom Villa", location: "City", rentCost: 2_500, purchaseCost: 350_000, taxRate: 25, image: "scripts/houses/images/villa.jpg", sleepQuality: 8, hygieneEffect: 2 },
  { id: 14, houseType: "Duplex", location: "Luxury Estate", rentCost: 1_200, purchaseCost: 120_000, taxRate: 15, image: "scripts/houses/images/duplex.jpg", sleepQuality: 7, hygieneEffect: 1 },
  { id: 15, houseType: "Modern Townhouse", location: "Village", rentCost: 1_500, purchaseCost: 150_000, taxRate: 15, image: "scripts/houses/images/town-house.jpg", sleepQuality: 6, hygieneEffect: 1 },
  { id: 16, houseType: "Eco-Friendly House", location: "City", rentCost: 1_800, purchaseCost: 200_000, taxRate: 20, image: "scripts/houses/images/eco-house.jpg", sleepQuality: 7, hygieneEffect: 1 },
  { id: 17, houseType: "3-Bedroom Ranch House", location: "City", rentCost: 600, purchaseCost: 35_000, taxRate: 5, image: "scripts/houses/images/eanch-house.jpg", sleepQuality: 4, hygieneEffect: 0 },
  { id: 18, houseType: "1-Bedroom Apartment", location: "City", rentCost: 500, purchaseCost: 30_000, taxRate: 5, image: "scripts/houses/images/one-bedroom-apt.jpg", sleepQuality: 4, hygieneEffect: 0 },
  { id: 19, houseType: "Mansion", location: "Luxury Estate", rentCost: 5_000, purchaseCost: 1_000_000, taxRate: 25, image: "scripts/houses/images/mansion.jpg", sleepQuality: 10, hygieneEffect: 3 },
  { id: 20, houseType: "2-Bedroom Traditional House", location: "Village", rentCost: 300, purchaseCost: 15_000, taxRate: 5, image: "scripts/houses/images/trad-house.jpg", sleepQuality: 4, hygieneEffect: -1 },
  { id: 21, houseType: "Mud Hut", location: "Village", rentCost: 80, purchaseCost: 9_500, taxRate: 5, image: "scripts/houses/images/mud-house.jpg", sleepQuality: 1, hygieneEffect: -2 },
  { id: 22, houseType: "1-Bedroom Bungalow", location: "Village", rentCost: 450, purchaseCost: 28_000, taxRate: 5, image: "scripts/houses/images/bungalow-village.jpg", sleepQuality: 4, hygieneEffect: 0 }
];
